Mobile menu using javaScript
oovillagran/Portfolio-project pull request #10
Opened 2023-03-14 17:42 UTC by oovillagran

For this milestone of my portfolio website, I implemented the mobile menu using JavaScript tools, I used the Figma Template number 1 for this project.

The general requirements of this milestone are:
- [ ] No linter errors.
- [ ] Correct use of GitHub flow.
- [ ] Work documented in a professional way.

**Project Requirements**
- [ ] When the user clicks (or taps) the hamburger button, the mobile menu appears.
- [ ] When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- [ ] When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- [ ] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2023-03-16 16:31 UTC, divinecharlotte requested changes
Hi @oovillagran   ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100:
- No linters errors :heavy_check_mark:
- Descriptive commit messages :heavy_check_mark:
- clean code :heavy_check_mark:
- Descriptive PR :heavy_check_mark:


![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes :recycle:
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 16:31 UTC, divinecharlotte commented on script.js
> +  // barDiv.style.padding = '50%';
- [x] kindly consider removing  commented codes it makes your code look messy

2023-03-16 16:31 UTC, divinecharlotte commented on script.js
> +  popDiv.appendChild(uList);
- [ ] kindly consider removing the the margin left and top to this part check the below image for more clarrification

- your design 👇 
- <img width="467" alt="Screen Shot 2023-03-16 at 18 23 57" src="https://user-images.githubusercontent.com/60146030/225687024-f5ed866d-6598-46bc-b6c9-540fc0d23ed4.png">
- Figma design 👇 
<img width="294" alt="Screen Shot 2023-03-16 at 18 28 44" src="https://user-images.githubusercontent.com/60146030/225688042-7ec2bcf5-6a09-4d50-badb-5a673e8624c6.png">
 this make your design a perfect duplicate of the provided design

2023-03-16 20:00 UTC, oovillagran commented on script.js
> +  popDiv.appendChild(uList);
Thank you @divinecharlotte, I appreciate your comments!! 👍

2023-03-17 00:55 UTC, Reem-lab approved these changes
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed GitHub flow ✅
- No Linters error 🤩🔥💯
- Great working on the functionality and design 🔥🔥
- Professional README 🔥✨💯💯
- Descriptive PR 🤩💯


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 02:44 UTC, oovillagran commented
Thank you so much @Reem-lab!!!

2023-03-17 02:45 UTC, merged